apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: apps
spec:
  interval: 1m
  chart:
    spec:
      chart: charts/service-chart
      version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: apps
      interval: 1m
  values:
    replicaCount: 3
    image:
      repository: hello-world
      tag: "latest"