apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: podinfo
  namespace: apps
spec:
  url: https://github.com/cristianrb/fleet-infra
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/